inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2 # closest to required_ruby_version of '>= 1.8.6'
  NewCops: enable


# Even the reference in the documentation suggests that you should prefer
# `alias_method` vs `alias`, so I don't understand why that isn't the default.
Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

# Enumerable#each_with_object only available since Ruby v1.9
Style/EachWithObject:
  Enabled: false

# Kernel#__dir__ has only been available since Ruby v2.0
Style/ExpandPathArguments:
  Enabled: false

# ruby19 style has only been supported since Ruby v1.9
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# I'm not keen on this cop, because it's easy to miss the conditional
# I think the results are particularly unhelpful when Metrics/LineLength is big
Style/IfUnlessModifier:
  Enabled: false
